version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"  # Assuming your Gemfile is in the root
    schedule:
      interval: "weekly"
      day: "monday"
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "nokogiri"
        versions: ["<1.15.0"]
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 3
