version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"                  # adjust if Gemfile is nested
    schedule:
      interval: "weekly"            # or "daily" / "monthly"
      day: "monday"                 # optional: spread PRs out
    allow:
      - dependency-type: "direct"   # only update top-level gems
    ignore:
      - dependency-name: "nokogiri" # remove or adjust if needed
        versions: ["<1.15.0"]       # avoid spammy updates
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 3     # avoid CI clutter
