    - name: Install dependencies
      run: bundle install

    - name: Build Jekyll site
      run: bundle exec jekyll build

    - name: Check for broken links (optional)
      run: bundle exec htmlproofer ./_site
